"""Phase 2v: strip Alex-era provenance tags from all rows.

These tags don't describe the paper, they describe the pipeline that added it:
  - alex-new
  - alex-recovery
  - incomplete-metadata
  - robert-j-barry  (auto-classifier guess; will be regenerated by structured tags)
  - not-robert-j-barry  (manual correction of auto-classifier; same)
  - barry-bibliography  (auto-classifier; same)
  - pdf-missing  (KEEP - we just set this in recover_v2 for genuinely lost PDFs)

The structured tags from evaluate_paper.py (domain/methodology/quality/custom_tags)
are NOT touched.

Usage:
  python pipeline/phase_2v_strip_junk_tags.py             # dry-run
  python pipeline/phase_2v_strip_junk_tags.py --execute   # apply
"""
import argparse
import json
import sqlite3
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "pipeline"))
import config  # noqa: E402
import papers_db  # noqa: E402

JUNK_TAGS = {
    "alex-new",
    "alex-recovery",
    "incomplete-metadata",
    "robert-j-barry",
    "not-robert-j-barry",
    "barry-bibliography",
}

KEEP_TAGS = {"pdf-missing"}  # set in recover_v2, still useful


def parse_tags(value):
    """Normalize whatever tags field looks like to a list of strings."""
    if not value:
        return []
    if isinstance(value, list):
        # Flatten nested if any
        out = []
        for x in value:
            if isinstance(x, str):
                # Sometimes stored as the literal "not-robert-j-barry,[\"alex-new\",...]"
                if x.startswith("[") or "," in x and "[" in x:
                    try:
                        parsed = json.loads(x)
                        if isinstance(parsed, list):
                            out.extend(parsed)
                            continue
                    except Exception:
                        pass
                    # Comma-split as fallback
                    if "," in x:
                        for p in x.split(","):
                            out.append(p.strip().strip("\""))
                        continue
                out.append(x)
            elif isinstance(x, list):
                out.extend(x)
        return out
    if isinstance(value, str):
        try:
            v = json.loads(value)
            if isinstance(v, list):
                return parse_tags(v)
        except Exception:
            pass
        return [value]
    return []


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--execute", action="store_true")
    args = ap.parse_args()

    print("=" * 70)
    print(f"Phase 2v: strip junk tags (mode: {'EXECUTE' if args.execute else 'DRY RUN'})")
    print("=" * 70)

    all_meta = papers_db.get_all_metadata()
    print(f"Total rows: {len(all_meta)}")

    # Survey current tag distribution
    tag_counts = Counter()
    rows_affected = []
    for p in all_meta:
        tags = parse_tags(p.get("tags"))
        for t in tags:
            tag_counts[t] += 1
        cleaned = [t for t in tags if t not in JUNK_TAGS]
        if cleaned != tags:
            rows_affected.append((p.get("id"), tags, cleaned))

    print()
    print("Current tag distribution (top 20):")
    for tag, cnt in tag_counts.most_common(20):
        marker = "[JUNK]" if tag in JUNK_TAGS else "[KEEP]" if tag in KEEP_TAGS else ""
        print(f"  {cnt:5d}  {tag}  {marker}")
    print()
    print(f"Rows to update: {len(rows_affected)}")
    print()

    if rows_affected:
        print("Sample updates (first 10):")
        for pid, before, after in rows_affected[:10]:
            removed = [t for t in before if t in JUNK_TAGS]
            print(f"  {pid}:")
            print(f"    before: {before}")
            print(f"    after:  {after}")
            print(f"    removed: {removed}")
        print()

    if not args.execute:
        print("DRY RUN. Pass --execute to apply.")
        return

    from papers_db import _serialize_field

    conn = sqlite3.connect(str(config.DB_PATH), timeout=60)
    try:
        for pid, before, after in rows_affected:
            conn.execute("UPDATE papers SET tags = ? WHERE id = ?",
                         (_serialize_field(after), pid))
        conn.commit()
        print(f"Stripped junk tags from {len(rows_affected)} rows.")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
